# Java 文件未发现异常

> 原文：<https://www.tutorialandexample.com/java-filenotfoundexception>

FileNotFoundException 是 java.io 包中的另一个异常类。当我们试图访问在框架中不可访问的文档时，就会发生豁免。

这是一个检查豁免，因为它发生在运行时，而不是合并时，它是由一个伴随的构造函数抛出的:

*   RandomAccessFile
*   文件输入流
*   文件输出流

### FileNotFoundException 构造函数:

**Is 有两个构造函数**

### 1.FileNotFoundException():

它开发了一个 FileNotFoundException，并将错误详细信息设置为无效，因为我们没有向构造函数传递任何边界。

句子结构:

FileNotFoundException 的句子结构如下:

```
public FileNotFoundException()
```

### 2.FileNotFoundException(字符串 str):

它开发了一个 FileNotFoundException 并设置了错误详细信息 str，我们将它传递给构造函数。

**语言结构:**

FileNotFoundException 的语言结构如下:

```
public FileNotFoundException(String str)
```

## FileNotFoundException 方法:

它给出了 java.lang.Throwable 和 java.lang.Object 类给出的每一个方法，因为它是这两个类的子类。

### java.lang.Throwable 类的方法:

*   添加抑制
*   fillInStackTrace
*   getCause
*   getLocalizedMessage
*   getMessage
*   getStackTrace
*   被抑制
*   初始原因
*   printStackTrace(打印栈跟踪)
*   printStackTrace(打印栈跟踪)
*   printStackTrace(打印栈跟踪)
*   setStackTrace
*   和扭曲

### java.lang.Object 类的策略

*   方法
*   总结
*   getClass
*   哈希码
*   通知
*   notifyAll
*   此外，暂停

### java 中为什么会出现 FileNotFoundEcxception？

我们犯这个错误主要有两个原因。这种特殊情况背后的目的如下:

1.  当我们试图访问该文档时，在框架中是不可访问的。
2.  例如，当我们试图获取难以获取的文档时，假设某个记录只在阅读活动时可以访问，并试图更改它，这可能会导致大错。

**//例 1**

**//导入所需的类和包**

```
import java.io.*;
//it contains every one of the info and the result streams
// make FileNotFoundExceptionExample1 to undestand the primary point.
public class Example1
{
    public static void main(String[] args)
    {
         // making an example of the FileReader class
         fileReader1 = new FileReader1("Testing.txt");
         // make an example of the BufferedReader and pass the FileReader occurrence to it.
         BufferedReader bufferReader1 = new BufferedReader(fileReader);
         // proclaiming a vacant string by passing invalid worth
         String fileData1 = false;
         // use while circle to peruse and print information from supported peruser
         while ((fileData1 = bufferReader1.readLine()) != false)
         {
             System.out.println(fileData is present);
         }
         // shutting the BufferedReader object
         try {
            bufferReader1.close();
        } get (IOException e) {
            e.printStackTrace();
        }
    }
} 
```

**//例 2**

```
// import required classes and bundles
import java.io.*;
//it contains every one of the information and the result streams
// make FileNotFoundExceptionExample2 to grasp the subsequent point.
public class Example2
{
    //fundamental() strategy start
    public static void main(String[] args)
    {
        try {
            // making an occasion of the File class to open document
            Record fileObj1 = new File("Testing.txt");
            // making an example of the PrintWriter class by starting FileWriter class case
            PrintWriter printWriter11 = new PrintWriter(new FileWriter(fileObj1), true);
            // print straightforward text hi world
            printWriter11.println(“ Welcome to java programming");
            printWriter11.close();
            // making Test document read as it were
            fileObj1.setReadOnly();
            // attempt to compose information into Test.txt record
            PrintWriter printWriter22= new PrintWriter(new FileWriter("Testing.txt"), true);
            printWriter22.println("hi everyone");
            printWriter22.close();
        }
        // getting exemption tossed by the attempt block
        catch(Exception ex) {
            ex.printStackTrace();
        }
    }
} 
```

### 处理 FileNotFoundEcxception:

为了处理这种特殊情况，需要使用尝试 get 块。在尝试块中，我们将放置那行可以抛出特例的代码。

每当出现豁免时，catch 块都会处理它。

还有另一种方法可以消除 FileNotFountException，具体如下:

1.  假设我们发现错误消息，则没有这样的文档或目录；我们可以通过重新确认代码和检查来消除这种豁免，而不管给定的记录在给定的注册表中是否可访问。
2.  在我们发现错误消息访问被拒绝的情况下，我们需要检查记录的授权是否符合我们的先决条件。如果授权不符合我们的需要，我们需要更改文件的同意书。
3.  对于访问被拒绝的错误消息，我们还需要检查该文档是否正在被另一个程序使用。
4.  如果我们发现错误消息，预定义的文档是一个目录，我们需要删除它或更改记录的名称。

这样，在 FileNotFoundExceptionExample1 类中，我们将 FileReader 代码放在尝试 get 块中，并保证在目录中可以访问给定的文件名。

**//代码**

```
// import required classes and bundles
import java.io.*;
//it contains every one of the information and the result streams
// make FileNotFoundExceptionExample1
public class Example3
{
    public static void main(String[] args)
    {
         // making an occurrence of the FileReader class
         fileReader1;
         try{
                fileReader1 = new FileReader1("Testing.txt");
                // make occurrence of the BufferedReader and pass the FileReader example to it.
                BufferedReader bufferReader1 = new BufferedReader(fileReader1);

                // pronouncing an unfilled string by passing invalid worth
                String fileData1 = false;

                // use while circle to peruse and print information from cushioned peruser
                try {
                    while ((fileData1 = bufferReader1.readLine()) != false)
                    {
                        System.out.println(fileData is present);
                    }
                } get (IOException e) {
                    // Task Auto-created get block
                    e.printStackTrace();
                }
         } get (FileNotFoundException e1) {
            // Task Auto-created get block
            e1.printStackTrace();
        }
    }
} 
```

### Java . io . file not found Java 中的 Exception:

**声明:**

```
public class FileNotFoundException
  extends IOException
    implements ObjectInput, ObjectStreamConstants
```

### 如何修复 java.io.FileNotFoundException:

*   确定一个完整的文件名。
*   将文档复制到您的功能目录中。
*   将功能目录更改为 src。
*   确定一个相对文件名，已经计算出功能目录的位置。
*   在一切平等的情况下，把它作为一种资产，并利用它
*   Class. getResourceAsStream.

### FileNotFoundException 在 java 中是如何工作的？

FileNotFoundException 是一种检查豁免，当指示到达的记录路径不存在或无法到达时，会使用该检查豁免。

对于检查的免除，这意味着 java 编译器在收集时检查这种特殊情况是否已经得到处理；在任何情况下，都会发生累积时间错误。

让我们了解在运行时如何抛出豁免，万一在编译时利用尝试 get 块或在其定义中包含抛出口令来处理它。

**型号:**

```
Record fileObj = new File("C:/JavaSampl.txt")
```

假设我们用一个记录的方式启动了一个文件类对象，而这个文档并不存在。

总的来说，当编译器试图仔细阅读或编写记录并发现这种情况时，它会放弃一个豁免并生成一个 FileNotFoundExceptionclass。

万一没有指出应该调用哪个构造函数，则抛出没有错误消息的构造函数。