# Java . net . connection 异常

> 原文:[https://www . tutorialandexample . com/Java-net-connection exception](https://www.tutorialandexample.com/java-net-connectionexception)

java . net . connect exception:Connection rejected:接口是最连续发生的事情，在产品处于客户机-服务器工程的任何点上组织 Java 中的特殊情况，并试图建立从客户机到服务器的 TCP 关联。我们想谨慎处理特殊情况，以满足通信问题。

java.net.ConnectException 特例是最广泛认可的与系统管理相关的 java 例外之一。我们可能会在设计从客户端应用程序到服务器的 TCP 关联时遇到这种情况。因为它是一个检查过的豁免，我们应该在代码中适当地处理它，试图得到一个阻塞。

**Java . net . connection 异常原因:连接被拒绝异常**

1.  万一服务器没有运行。一般来说，像 8080(用于 tomcat)、3000 或 4200(用于 respond/rakish)、3306(MySQL)、27017(MongoDB)这样的端口，或者被几个不同的专家所涉及，或者彻底关闭，例如，某个场合没有开始。
2.  这里和那里，服务器可能正在运行，但是，根据一些被取代的设置等等，没有在端口上调谐。
3.  通常，为了安全起见，防火墙会在那里，如果它拒绝通信。
4.  偶然地，一些不可接受的端口在端口或给定的任意端口年龄号中被引用。
5.  关联字符串数据错误:例如，在使用 JDBC 连接数据库时，如果我们给了一个错误的密码，异常可能会出现。
6.  由于客户机和服务器都包括在内，所以它们都应该在一个像局域网或万维网这样的组织中。它会在客户端抛出一个豁免。
7.  我们试图连接的服务器基本上没有启动。以这种方式，我们不能得到一个关联。
8.  我们用来连接服务器的主机和端口组合可能是错误的
9.  防火墙可能会阻止来自显式 IP 位置或端口的关联

**例 1:**

显示 java.net.ConnectionException 异常的示例程序:

```
// program to demonstrate the java.net.Connection Exception
import java.io.*;
import java.net.*;
importjava.util.*;
// class with main
public class HelloWorld {
	public static void main(String[] args)
	{
    // main method
		// defining the local hostname and the value of the local host is 127.0.0.1
		String host = "127.0.0.1";
		// defining the port and the port id must be 8080 or 8000
		// the post id should not be 100 
		// if it is rather than 8080 or 8000 the exception rises
		int port = 100;
		// Try block to check for exceptions
		try (Socket so = new Socket(host, port)) {
			// defining an InputStream to read the socket data
			InputStream input = so.getInputStream();
			InputStreamReaderis = new InputStreamReader(input);
int da;
			StringBuilder output= new StringBuilder();
			// reading the data from the input stream
			while ((da = isr.read())!= -1) {
				output.append((char)da);
			}
		}
		// Handling the Exception using catch block
		catch (IOException e) {

			/* If the given hostname and port number are invalid, the network can't be laid out, and consequently blunder is tossed Exception will happen when the attachment will not be reachable */
			System.out.println("Connection Refused Exception as the given hostname and port are invalid : "+ e.getMessage());
		}
	}
}
```

**输出:**

<figure class="wp-block-image">![Java.net.ConnectionException](../Images/cb404d07d2e1b235e4fb61397f1dec2c.png)</figure>

输出是:Java-CP/tmp/9 blwnhzxar hello world

连接被拒绝异常，因为给定的主机名和端口无效:连接被拒绝(连接被拒绝)

**例 2:**

建立数据库连接的程序

```
// java program to setup the connection between the Java and database
import java.io.*;
importjava.util.*;
importjava.sql.*; // importing sql package
classHelloWorld
{
public static void main(String args[])
    {
// checking the Exception using the try block
try {
	// initializing the connection object value as NULL
	Connection connect = null;
	String dr = "com.MySQL.jdbc.Driver";
	// Step 2: loading the driver class 
	// Here, in the event that IP address isn't your localhost, need to determine that or explicit location
	String IP = "local"
		// giving the port id as 3306
		String urlmysql://IPADDRESS:3306/= "JDBC:mysql://IP:3306/
	// followed as DB = MySQL username= Scott, password=tiger
	String DB = "<your dbname>";
	String dbUser = "<username>";
	String dbPasswd = "<password>";
	// By using the forName() method, we are loading the driver class
	Class.forName(driver).newInstance();
	// making the connection using the connection manager
	co = DriverManager.getConnection(url1 + DB, dbUser,dbPasswd);

	// Displaying the successful message if the connection is set up successful
	System.out.println(" The database connected sucessfully");
}
// Handling the Exception using the catch block
catch (IOException e) {
// Exemption will happen when the IPAddress and port number are confounded By pinging. We can address that
	System.out.println("Connection Refused Exception as the given hostname and port are invalid : "+ e.getMessage());
}
}
}
```